const CENTRAL_CFG=window.PCM_CENTRAL||{endpoint:'',enabled:false,timeoutMs:15000};
const centralInFlight=new Map();
function centralConfigured(){return !!(CENTRAL_CFG.enabled&&String(CENTRAL_CFG.endpoint||'').startsWith('https://script.google.com/'))}
function updateReleaseRecord(id,fn){let a=releaseRecords(),i=a.findIndex(x=>x.id===id);if(i<0)return null;let n=fn({...a[i]});if(!n)return a[i];a[i]=n;try{localStorage[HISTORY_KEY]=JSON.stringify(a.slice(0,HISTORY_LIMIT));return n}catch(e){console.error(e);return null}}
function centralState(r){return r&&r.central?r.central:{status:centralConfigured()?'pending':'device-only',attempts:0,receipt:'',syncedAt:'',lastError:''}}
function setCentralState(id,patch){return updateReleaseRecord(id,r=>({...r,central:{...centralState(r),...patch}}))}
function centralBadge(r){let s=centralState(r);if(s.status==='saved')return'<span class="centralBadge saved">✓ CENTRAL</span>';if(s.status==='syncing')return'<span class="centralBadge syncing">↻ SYNCING</span>';if(s.status==='pending'||s.status==='failed')return'<span class="centralBadge pending">! PENDING</span>';return'<span class="centralBadge device">DEVICE</span>'}
function centralBanner(r){let s=centralState(r);if(s.status==='saved')return`<div class="savedBanner centralSaved">✓ SAVED CENTRALLY${s.receipt?` · ${esc(s.receipt)}`:''}</div>`;if(s.status==='syncing')return'<div class="savedBanner centralSyncing">↻ SAVING CENTRALLY…</div>';if(centralConfigured())return'<div class="saveWarning">! SAVED ON DEVICE — CENTRAL SYNC PENDING</div>';return'<div class="savedBanner">✓ SAVED ON THIS DEVICE</div>'}
function centralPayload(r){return{schema:1,id:r.id,completedAt:r.completedAt,manager:r.manager||'',office:r.office||'',route:r.route||'',address:r.address||'',municipality:r.municipality||'',jurisdiction:r.jurisdiction||'',currentRelease:r.currentRelease||'',managerClass:r.managerClass||'',checks:r.checks||{},decision:r.decision||'',decisionReason:r.decisionReason||'',notes:r.notes||'',snapshot:r.snapshot||''}}
function cleanupCentral(id){let x=centralInFlight.get(id);if(!x)return;clearTimeout(x.timer);try{x.form&&x.form.remove()}catch{}try{x.frame&&x.frame.remove()}catch{}centralInFlight.delete(id)}
function renderIfUseful(){if(view==='history'||(view==='release'&&releaseStep>=6))render()}
function submitCentralRecord(r){if(!centralConfigured()||!r||!r.id||centralInFlight.has(r.id)||!navigator.onLine)return false;let st=centralState(r);if(st.status==='saved')return true;setCentralState(r.id,{status:'syncing',attempts:(st.attempts||0)+1,lastError:''});let token=Math.random().toString(36).slice(2),frame=document.createElement('iframe');frame.name='pcmCentral_'+token;frame.hidden=true;frame.setAttribute('aria-hidden','true');let formEl=document.createElement('form');formEl.method='POST';formEl.action=CENTRAL_CFG.endpoint;formEl.target=frame.name;formEl.hidden=true;let input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify(centralPayload(r));formEl.appendChild(input);document.body.append(frame,formEl);let timer=setTimeout(()=>{cleanupCentral(r.id);setCentralState(r.id,{status:'pending',lastError:'No central receipt received; will retry.'});renderIfUseful()},CENTRAL_CFG.timeoutMs||15000);centralInFlight.set(r.id,{frame,form:formEl,timer});try{formEl.submit();return true}catch(e){cleanupCentral(r.id);setCentralState(r.id,{status:'failed',lastError:String(e)});renderIfUseful();return false}}
window.addEventListener('message',e=>{if(!/^https:\/\/script\.google(?:usercontent)?\.com$/.test(e.origin))return;let d=e.data;if(!d||d.type!=='PCM_CENTRAL_SAVE'||!d.id)return;cleanupCentral(d.id);if(d.ok)setCentralState(d.id,{status:'saved',receipt:d.receipt||'',row:d.row||'',serverDecision:d.decision||'',syncedAt:new Date().toISOString(),lastError:''});else setCentralState(d.id,{status:'failed',lastError:d.error||'Central save failed.'});renderIfUseful()});
function syncReleaseIfNeeded(r){if(!centralConfigured()||!r)return;let s=centralState(r);if(s.status==='saved'||s.status==='syncing')return;submitCentralRecord(r)}
function retryPendingCentral(){if(!centralConfigured()||!navigator.onLine)return;releaseRecords().filter(r=>['pending','failed','device-only'].includes(centralState(r).status)).slice(0,5).forEach((r,i)=>setTimeout(()=>syncReleaseIfNeeded(r),i*500))}
window.addEventListener('online',()=>retryPendingCentral());
