const HISTORY_KEY='pcmReleaseHistoryV1',HISTORY_LIMIT=100;
function releaseRecords(){try{let a=JSON.parse(localStorage[HISTORY_KEY]||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function makeReleaseRecord(){
  if(!sel||!form.completedAt)return null;
  form.releaseId=form.releaseId||pcmNewReleaseId();form.releaseDate=form.releaseDate||localDateISO(new Date(form.completedAt));
  let d=decision(),p=window.PCM_PROVENANCE||{};
  return{schema:2,id:form.releaseId,releaseId:form.releaseId,releaseDate:form.releaseDate,scope:releaseScopeText(form.releaseDate),completedAt:form.completedAt,savedAt:new Date().toISOString(),manager:form.manager||'',office:form.office||'',route:form.route||'',address:form.address||'',municipality:sel.name,county:sel.county||'',jurisdiction:sel.jurisdiction||'',currentRelease:sel.release,managerClass:sel.managerClass||'',checks:{time:form.c.time||'',signs:form.c.signs||'',materials:form.c.materials||'',permit:form.c.permit||'',appointment:form.c.appointment||''},decision:d[0]?'DEPLOY':'DO NOT DEPLOY',decisionReason:d[1],notes:form.notes||'',snapshot:db.meta.snapshotDate,appVersion:p.appVersion||window.PCM_BUILD_VERSION||'—',datasetSha256:p.datasetSha256||'—',buildCommit:window.PCM_BUILD_COMMIT||'—'}
}
function saveCurrentRelease(){let r=makeReleaseRecord();if(!r)return null;let a=releaseRecords(),i=a.findIndex(x=>x.id===r.id);if(i>=0)a[i]=r;else a.unshift(r);a.sort((x,y)=>String(y.completedAt).localeCompare(String(x.completedAt)));try{localStorage[HISTORY_KEY]=JSON.stringify(a.slice(0,HISTORY_LIMIT));return r}catch(e){console.error(e);return null}}
function recordText(r){return['PARADISE CANVASS DAILY RELEASE',`Release ID: ${r.releaseId||r.id||'—'}`,`Release Date: ${r.releaseDate||String(r.completedAt||'').slice(0,10)||'—'}`,`Completed: ${r.completedAt?new Date(r.completedAt).toLocaleString():'—'}`,`Manager: ${r.manager||'—'}`,`Office / Team: ${r.office||'—'}`,`Territory / Route: ${r.route||'—'}`,`Address / Boundary: ${r.address||'—'}`,`City / Area: ${r.municipality||'—'}`,`Legal Jurisdiction: ${r.jurisdiction||'—'}`,`Current Release: ${r.currentRelease||'—'}`,`Time Window: ${r.checks?.time||'NOT SET'}`,`Signs / Access / Refusal: ${r.checks?.signs||'NOT SET'}`,`Materials / ROW: ${r.checks?.materials||'NOT SET'}`,`Permit / ID / Entity: ${r.checks?.permit||'NOT SET'}`,`Appointment-Only / Script / HSS: ${r.checks?.appointment||'NOT SET'}`,`Final Decision: ${r.decision||'—'}`,`Decision Reason: ${r.decisionReason||'—'}`,`Scope: ${r.scope||'Valid only for the recorded date and route/address boundary.'}`,`Notes: ${r.notes||'—'}`,`Controlled Snapshot: ${r.snapshot||'—'}`,`App Version: ${r.appVersion||'Legacy record'}`,`Dataset SHA-256: ${r.datasetSha256||'Legacy record'}`,`Build Commit: ${r.buildCommit||'Legacy record'}`,`Record Schema: ${r.schema||1}`].join('\n')}
async function copyRecord(r){try{await navigator.clipboard.writeText(recordText(r));toast('Release record copied.')}catch{toast('Copy failed on this browser.')}}
async function shareRecord(r){const text=recordText(r);if(navigator.share){try{await navigator.share({title:`Canvass Release — ${r.municipality||''}`,text});return}catch(e){if(e&&e.name==='AbortError')return}}return copyRecord(r)}
function csvCell(v){let s=String(v??'');return/[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function releaseCsv(a){const h=['releaseId','releaseDate','completedAt','manager','office','route','address','municipality','county','jurisdiction','currentRelease','time','signs','materials','permit','appointment','decision','decisionReason','scope','notes','snapshot','appVersion','datasetSha256','buildCommit','schema'];let rows=[h];for(const r of a)rows.push([r.releaseId||r.id||'',r.releaseDate||'',r.completedAt||'',r.manager||'',r.office||'',r.route||'',r.address||'',r.municipality||'',r.county||'',r.jurisdiction||'',r.currentRelease||'',r.checks?.time||'',r.checks?.signs||'',r.checks?.materials||'',r.checks?.permit||'',r.checks?.appointment||'',r.decision||'',r.decisionReason||'',r.scope||'',r.notes||'',r.snapshot||'',r.appVersion||'',r.datasetSha256||'',r.buildCommit||'',r.schema||1]);return rows.map(row=>row.map(csvCell).join(',')).join('\n')}
function downloadText(name,text,type='text/plain'){try{let b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Export created.')}catch(e){console.error(e);toast('Export failed on this browser.')}}
function exportCsv(a){downloadText(`Paradise_Canvass_Releases_${localDateISO()}.csv`,releaseCsv(a),'text/csv')}
function exportJson(a){downloadText(`Paradise_Canvass_Releases_${localDateISO()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),records:a},null,2),'application/json')}
function history(){
  let a=releaseRecords();
  M.innerHTML=`<div class="head"><div><h2>Release History</h2><p>Automatically saved on this device</p></div>${a.length?`<button class="back" id="copyAll">Copy all</button>`:''}</div><div class="notice"><b>Device record.</b> Completed releases are saved automatically on this phone. Clearing browser/site data can remove this history. Use CSV/JSON export when a durable copy is needed.</div>${a.length?`<div class="exportBar"><button class="btn secondary" id="exportCsv">Export CSV</button><button class="btn secondary" id="exportJson">Export JSON</button></div><div class="historyList">${a.map((r,i)=>`<section class="historyCard ${r.decision==='DEPLOY'?'yes':'no'}"><button class="historyHead" data-open="${i}"><span class="historyIcon">${r.decision==='DEPLOY'?'✓':'✕'}</span><span class="historyMain"><b>${esc(r.municipality)}</b><small>${esc(r.completedAt?new Date(r.completedAt).toLocaleString():'—')} · ${esc(r.manager||'No manager')}</small></span><span class="historyDecision">${esc(r.decision)}</span></button><div class="historyDetail" id="hist${i}" hidden>${row('Release date',r.releaseDate||String(r.completedAt||'').slice(0,10)||'—','strong')}${row('Exact route / address',r.address,'strong')}${row('Manager',r.manager||'—')}${row('Office / Team',r.office||'—')}${row('Territory / Route',r.route||'—')}${row('Reason',r.decisionReason)}${row('Scope',r.scope||'Valid only for the recorded date and route/address boundary.')}<div class="summaryCheck"><span>Time window</span><b class="state ${esc(r.checks?.time||'MISSING')}">${esc(r.checks?.time||'NOT SET')}</b></div><div class="summaryCheck"><span>Signs / refusal</span><b class="state ${esc(r.checks?.signs||'MISSING')}">${esc(r.checks?.signs||'NOT SET')}</b></div><div class="summaryCheck"><span>Materials / ROW</span><b class="state ${esc(r.checks?.materials||'MISSING')}">${esc(r.checks?.materials||'NOT SET')}</b></div><div class="summaryCheck"><span>Permit / ID</span><b class="state ${esc(r.checks?.permit||'MISSING')}">${esc(r.checks?.permit||'NOT SET')}</b></div><div class="summaryCheck"><span>Appointment / HSS</span><b class="state ${esc(r.checks?.appointment||'MISSING')}">${esc(r.checks?.appointment||'NOT SET')}</b></div><div class="historyMeta"><small class="recordId">Release ID: ${esc(r.releaseId||r.id||'Legacy')}</small><small>Snapshot: ${esc(r.snapshot||'—')} · App: ${esc(r.appVersion||'Legacy record')}</small><small>Dataset SHA-256: ${esc(r.datasetSha256||'Legacy record')}</small><small>Build: ${esc(r.buildCommit||'Legacy record')}</small></div><div class="shareRow"><button class="btn secondary historyCopy" data-copy="${i}">Copy record</button><button class="btn secondary historyShare" data-share="${i}">Share record</button></div></div></section>`).join('')}</div>`:`<div class="empty"><h2>No completed releases yet</h2><p>Your completed Daily Releases will appear here automatically.</p><button class="btn primary" id="goLookup">Start a lookup</button></div>`}`;
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{let e=document.getElementById('hist'+b.dataset.open);e.hidden=!e.hidden});
  document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyRecord(a[Number(b.dataset.copy)]));
  document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareRecord(a[Number(b.dataset.share)]));
  if(document.getElementById('copyAll'))document.getElementById('copyAll').onclick=async()=>{try{await navigator.clipboard.writeText(a.map(recordText).join('\n\n----------------\n\n'));toast(`${a.length} records copied.`)}catch{toast('Copy failed on this browser.')}};
  if(document.getElementById('exportCsv'))document.getElementById('exportCsv').onclick=()=>exportCsv(a);
  if(document.getElementById('exportJson'))document.getElementById('exportJson').onclick=()=>exportJson(a);
  if(document.getElementById('goLookup'))document.getElementById('goLookup').onclick=()=>setView('lookup');
}
