function releaseHeader(){return`<div class="head"><div><h2>Daily Check</h2><p>${esc(sel.name)} · ${esc(status(sel).label)}</p></div><button class="back" id="cityBack">City</button></div>`}
function progress(step){let pct=Math.max(0,Math.min(100,(step/5)*100));return`<div class="progressWrap"><div class="progressMeta"><b>${step?`CHECK ${step} OF 5`:'ROUTE SETUP'}</b><span>${step?`${Math.round(pct)}%`:'Before checks'}</span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
function bindCityBack(){document.getElementById('cityBack').onclick=()=>setView('lookup')}
function setupRequirementHint(){let miss=[];if(!form.manager.trim())miss.push('manager');if(!form.route.trim())miss.push('territory / route');if(!form.address.trim())miss.push('exact address / boundary');if(!form.confirm)miss.push('address confirmation');return miss.length?'Still needed: '+miss.join(', ')+'.':''}
function releaseSetup(){
  const block=currentDeployBlock(),age=typeof pcmSnapshotAgeDays==='function'?pcmSnapshotAgeDays():null,ready=releaseIdentityReady();
  M.innerHTML=`${releaseHeader()}${progress(0)}${block?`<div class="blockBanner"><b>UPDATE REQUIRED.</b> ${esc(block)}</div>`:''}${age!==null&&age>30&&!block?`<div class="staleBanner"><b>Check for an update.</b> These rules were last refreshed ${age} days ago.</div>`:''}<div class="scopeBanner"><b>Today only.</b> ${esc(releaseScopeText(localDateISO()))}</div><section class="wizardCard"><div class="wizardEyebrow">ROUTE DETAILS</div><h3>Confirm the route</h3><p class="wizardHelp">Enter the manager, route, and exact address or boundary. Then confirm the city/county rule matches the route.</p><div class="field"><label>Manager <span class="requiredMark">*</span></label><input id="manager" class="input" value="${esc(form.manager)}" placeholder="Manager name" autocomplete="name"></div><div class="field"><label>Office / Team</label><input id="office" class="input" value="${esc(form.office)}" placeholder="Office or team"></div><div class="field"><label>Territory / Route <span class="requiredMark">*</span></label><input id="route" class="input" value="${esc(form.route)}" placeholder="Neighborhood / route"></div><div class="field"><label>Exact Address / Route Boundary <span class="requiredMark">*</span></label><input id="address" class="input" value="${esc(form.address)}" placeholder="Exact street address or boundary" autocomplete="street-address"></div><div class="field"><label>City / County Rule</label><div class="input readonly">${esc(sel.jurisdiction)}</div></div><label class="confirm"><input id="confirm" type="checkbox" ${form.confirm?'checked':''}><span>I checked the address or route boundary and it matches the city/county rule shown above.</span></label><div id="requirementHint" class="validationHint">${esc(setupRequirementHint())}</div><button id="continue" class="btn primary wizardNext" ${ready?'':'disabled'}>START 5 CHECKS →</button></section><div class="notice"><b>Before canvassing:</b> all required route fields must be complete and all five checks must pass.</div>`;
  bindCityBack();
  const refresh=()=>{const b=document.getElementById('continue'),h=document.getElementById('requirementHint');if(b)b.disabled=!releaseIdentityReady();if(h)h.textContent=setupRequirementHint()};
  let bind=(id,k,store)=>document.getElementById(id).oninput=e=>{form[k]=e.target.value;if(store)localStorage[store]=e.target.value;refresh()};
  bind('manager','manager','pcmManager');bind('office','office','pcmOffice');bind('route','route');bind('address','address');
  document.getElementById('confirm').onchange=e=>{form.confirm=e.target.checked;refresh()};
  document.getElementById('continue').onclick=()=>{if(!releaseIdentityReady()){toast(currentDeployBlock()||setupRequirementHint()||'Complete the required route fields first.');return}form.releaseDate=localDateISO();releaseStep=1;release()};
}
function releaseCheck(){
  if(currentDeployBlock()){M.innerHTML=`${releaseHeader()}${progress(releaseStep)}<div class="blockBanner"><b>UPDATE REQUIRED.</b> ${esc(currentDeployBlock())}</div><section class="wizardCard"><h3>Update the app first</h3><p class="wizardHelp">New approved rules are available. Update the app before starting another route.</p></section>`;bindCityBack();return}
  let x=checks[releaseStep-1],current=form.c[x.key];
  M.innerHTML=`${releaseHeader()}${progress(releaseStep)}<div class="scopeBanner">${esc(releaseScopeText(form.releaseDate||localDateISO()))}</div><section class="wizardCard checkScreen"><div class="wizardEyebrow">STEP ${releaseStep} OF 5</div><h3>${esc(x.title)}</h3><p class="wizardHelp">${esc(x.help(sel)||'—')}</p><div class="bigSeg"><button data-v="PASS" class="${current==='PASS'?'PASS':''}"><b>✓ PASS</b><span>This is confirmed</span></button><button data-v="STOP" class="${current==='STOP'?'STOP':''}"><b>✕ STOP</b><span>Do not canvass</span></button><button data-v="ESCALATE" class="${current==='ESCALATE'?'ESCALATE':''}"><b>! REVIEW</b><span>Ask manager/compliance first</span></button></div><div class="wizardNav"><button id="prev" class="btn secondary">← BACK</button><span>${releaseStep} / 5</span></div></section>`;
  bindCityBack();
  document.querySelectorAll('.bigSeg button').forEach(b=>b.onclick=()=>{form.c[x.key]=b.dataset.v;if(b.dataset.v==='PASS')releaseStep=releaseStep<5?releaseStep+1:6;else releaseStep=6;if(releaseStep===6&&!form.completedAt){form.completedAt=new Date().toISOString();form.releaseDate=form.releaseDate||localDateISO();form.releaseId=form.releaseId||pcmNewReleaseId()}release()});
  document.getElementById('prev').onclick=()=>{releaseStep=Math.max(0,releaseStep-1);release()};
}
