import {test,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
test.describe.configure({retries:0});
async function pick(page,name){await page.getByPlaceholder('Start typing a city…').fill(name);await page.locator('.opt').filter({hasText:name}).first().click()}
async function waitForServer(url,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,150))}throw new Error('Offline-test origin did not start')}

test('cached iPhone v3.12 keeps field answers and Paradise University core offline',async({page})=>{
  const origin='http://127.0.0.1:4183';const server=spawn('python3',['-m','http.server','4183','--bind','127.0.0.1'],{cwd:process.cwd(),stdio:'ignore'});
  try{
    await waitForServer(origin+'/index.html');await page.goto(origin+'/index.html');
    await expect.poll(async()=>page.evaluate(async()=>{await navigator.serviceWorker.ready;const keys=await caches.keys();const key=keys.find(k=>k.startsWith('pcm-field-'));if(!key)return{index:false,training:false,content:false,sourcefix:false,managerData:false,managerUi:false,salesData:false,salesUi:false,player:false,playerCss:false,key:null};const cache=await caches.open(key);return{index:!!(await cache.match('./index.html')),training:!!(await cache.match('./training-v1.js')),content:!!(await cache.match('./training-content-v1.js')),sourcefix:!!(await cache.match('./training-content-sourcefix-v1.js')),managerData:!!(await cache.match('./training-manager-v1-data.js')),managerUi:!!(await cache.match('./training-manager-v1-ui.js')),salesData:!!(await cache.match('./training-sales-v1-data.js')),salesUi:!!(await cache.match('./training-sales-v1-ui.js')),player:!!(await cache.match('./training-player-v1.js')),playerCss:!!(await cache.match('./training-player-v1.css')),key}}),{timeout:15000}).toMatchObject({index:true,training:true,content:true,sourcefix:true,managerData:true,managerUi:true,salesData:true,salesUi:true,player:true,playerCss:true,key:'pcm-field-v3-12-pu-v1-content5-2026-08-16'});
    await page.reload({waitUntil:'domcontentloaded'});await expect.poll(async()=>page.evaluate(()=>!!navigator.serviceWorker.controller),{timeout:10000}).toBeTruthy();server.kill('SIGTERM');await new Promise(r=>setTimeout(r,750));await expect.poll(async()=>{try{await fetch(origin+'/index.html');return false}catch{return true}},{timeout:5000}).toBeTruthy();await page.reload({waitUntil:'domcontentloaded',timeout:15000});
    await page.locator('#nTrain').click();await expect(page.getByRole('heading',{name:'Train. Practice. Advance.'})).toBeVisible();await page.getByRole('button',{name:/Career Path/}).first().click();await expect(page.getByRole('button',{name:/Canvass Manager Academy/})).toBeVisible();await page.getByRole('button',{name:/6\. Sales Rep/}).click();await expect(page.getByRole('button',{name:/1\. Preparation/})).toBeVisible();await expect(page.getByText(/CURRENT POLICY REQUIRED/)).toBeVisible();await page.locator('#nTrain').click();await page.getByRole('button',{name:/Videos & Audio/}).first().click();await expect(page.getByText('Tonality and Body Language',{exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:'PLAY'}).first()).toBeVisible();await page.locator('#nLook').click();
    await pick(page,'Boca Raton');await expect(page.locator('[data-field="door-hanger"] .val')).toHaveText('YES — HANG ON FRONT DOORKNOB / HANDLE.');await page.getByRole('button',{name:'Permit / permission'}).click();const panel=page.locator('#say');await expect(panel).toContainText('Our compliance review for Boca Raton does not require a separate route-specific canvasser permit');await expect(panel).toContainText('installation-day courtesy notice, not a sales offer');await expect(panel).toContainText('Government or law enforcement: do not argue or debate the law');
    await page.getByRole('button',{name:'New search'}).click();await pick(page,'Boynton Beach');await expect(page.locator('[data-field="hours"] .val')).toHaveText('Hours not confirmed - use Paradise’s normal route schedule.');
    await page.getByRole('button',{name:'New search'}).click();await pick(page,'Dania');await page.getByRole('button',{name:/RUN DAILY CHECK/}).click();await page.getByPlaceholder('Manager name').fill('Offline Test Manager');await page.getByPlaceholder('Neighborhood / route').fill('Offline Route A');await page.getByPlaceholder('Exact street address or boundary').fill('789 Offline Test Route');await page.getByRole('checkbox').check();await page.getByRole('button',{name:/START 5 CHECKS/}).click();for(let i=0;i<5;i++)await page.getByRole('button',{name:/PASS/}).click();await expect(page.locator('.finalDecision')).toContainText('APPROVED TO CANVASS');await expect(page.locator('.finalFacts')).toContainText('2026.08.14-v3.12');
  }finally{if(server.exitCode===null)server.kill('SIGTERM')}
});
