create table if not exists public.shows_app_calendar_research_controls (
  control_id text primary key,
  event_label text not null,
  event_start date not null,
  event_end date,
  profile_id text,
  disposition text not null check (disposition in ('PURSUE','WATCH','RESEARCH','SUPPRESS')),
  priority text not null check (priority in ('HIGH','MEDIUM','LOW')),
  identity_treatment text not null,
  price_text text,
  rationale text not null,
  verification_state text not null check (verification_state in ('CURRENT_WEB_VERIFIED','RECOVERED_AUDIT')),
  source_url text,
  calendar_visibility boolean not null default true,
  plan_year integer not null default 2026,
  research_batch text not null default '2026-09-13_FINAL_REMAINDER_2026_AUDIT',
  source_ref text not null default 'CHATGPT_ARCHIVE:2026-09-13_FINAL_REMAINDER_2026_AUDIT',
  active boolean not null default true,
  checked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.shows_app_calendar_research_controls enable row level security;

insert into public.shows_app_calendar_research_controls
(control_id,event_label,event_start,event_end,profile_id,disposition,priority,identity_treatment,price_text,rationale,verification_state,source_url,calendar_visibility)
values
('RQ4-2026-001','Florida Creatives Market — Port St. Lucie','2026-10-03','2026-10-04',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$500 sponsor vendor — Businesses/Services/Lead Gen/Brick & Mortar','Explicit business/services lead-gen sponsor-vendor lane; recovered final Q4 overlay.','CURRENT_WEB_VERIFIED','https://www.eventeny.com/events/vendor/?id=50951',true),
('RQ4-2026-002','Coral Springs Oktoberfest','2026-10-03','2026-10-03',NULL,'PURSUE','HIGH','PORTFOLIO_CHILD','$100 business booth in recovered audit','Business-booth control retained in final Q4 reconciliation; portfolio-child/non-additive treatment.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-003','Port St. Lucie Oktoberfest','2026-10-03','2026-10-03',NULL,'RESEARCH','MEDIUM','PORTFOLIO_CHILD','Business/company booth — price recheck','Retained as a portfolio-child Q4 control; exact current commercial terms require recheck.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-004','Fort Pierce Friday Fest — October','2026-10-02','2026-10-02',NULL,'PURSUE','MEDIUM','SERIES_REACTIVATION','Vendor/business route — terms recheck','Recovered municipal recurring-event control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-005','Martin County Fall Fest','2026-10-09','2026-10-09',NULL,'PURSUE','HIGH','UNRESOLVED','$250 10x10/sponsor control in recovered audit','Strong low-cost Q4 community-event control from final audit.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-006','GACTC Oktoberfest — Treasure Coast','2026-10-09','2026-10-11',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','$275 Business Services booth; Oct. 2 deadline in recovered audit','Business-services eligibility was explicitly recovered; identity/crosswalk remained open.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-007','Palm Bay Pumpkins & Palms','2026-10-10','2026-10-10',NULL,'PURSUE','HIGH','UNRESOLVED','Sponsor/vendor route — price recheck','Recovered as a low-cost municipal Q4 opportunity.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-008','Hollywood Hispanic Heritage Celebration','2026-10-10','2026-10-10',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','$150 informational/business vendor in recovered audit','Recovered business/informational vendor lane.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-009','Dania After Dark Oktoberfest','2026-10-10','2026-10-10',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','$750–$2,250 Business Exhibitor','Current application explicitly accepts business exhibitors and requires COI.','CURRENT_WEB_VERIFIED','https://www.eventeny.com/events/vendor/?id=52114',true),
('RQ4-2026-010','Deerfield Beach Fall Festival','2026-10-10','2026-10-10',NULL,'PURSUE','MEDIUM','UNRESOLVED','Vendor/sponsor route — direct eligibility recheck','Recovered as a final October control; commercial fit should remain explicit research until organizer confirmation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-011','Buckler West Palm Beach Craft Fair — October','2026-10-10','2026-10-11',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','$400 commercial 10x10 in recovered audit','Historical/same-series control; retained on calendar without adding a new canonical profile.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-012','Treasure Coast Marine Flea Market','2026-10-10','2026-10-11','HIST-039','WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Commercial route — current terms recheck','Official date correction to Oct. 10–11 superseded the stale Nov. 7–8 date; historical successor.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-013','Miami-Broward One Carnival','2026-10-11','2026-10-11',NULL,'WATCH','HIGH','SERIES_REACTIVATION','Corporate activation pricing anomaly — requote','Recovered corporate activation/sponsorship control; prior 10x20/10x10 pricing was anomalous and must not be treated as current without requote.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-014','Cars & Coffee Palm Beach — October','2026-10-11','2026-10-11',NULL,'WATCH','MEDIUM','SERIES_REACTIVATION','Quote required','Recovered recurring business/vendor opportunity.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-015','Chamber Approved Senior Services Show & Health Fair','2026-10-15','2026-10-15',NULL,'RESEARCH','MEDIUM','UNRESOLVED','Commercial terms recheck','Retained in the final Q4 survivor set; exact Paradise eligibility/cost requires current confirmation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-016','Jupiter HarbourFest','2026-10-16','2026-10-17',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','$850 Business Exhibitor in recovered audit','Two-day waterfront festival; final audit retained business-exhibitor treatment.','CURRENT_WEB_VERIFIED','https://www.jupiterharbourfest.org/faq',true),
('RQ4-2026-017','Riverwalk Fall Festival','2026-10-17','2026-10-17',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$150–$400 vendor; $500–$10,000 sponsor','Official event publishes vendor and sponsorship opportunities; 2,000+ annual attendance.','CURRENT_WEB_VERIFIED','https://www.goriverwalk.com/events/riverwalk-fall-festival',true),
('RQ4-2026-018','Wellington Fall Festival','2026-10-17','2026-10-17',NULL,'PURSUE','HIGH','UNRESOLVED','Vendor/business participation route — terms recheck','Recovered high-priority municipal event; current event date verified.','CURRENT_WEB_VERIFIED','https://www.wellingtonfl.gov/660/Fall-Festival',true),
('RQ4-2026-019','Pompano Beach Caribbean Fest','2026-10-17','2026-10-17',NULL,'WATCH','MEDIUM','UNRESOLVED','Vendor and sponsor applications available','Official city page provides both vendor and sponsor interest routes.','CURRENT_WEB_VERIFIED','https://www.pompanobeachfl.gov/events/pompano-caribbean-fest',true),
('RQ4-2026-020','Plantation Family Fall Festival','2026-10-17','2026-10-17',NULL,'WATCH','MEDIUM','UNRESOLVED','Vendor/sponsor eligibility recheck','Recovered October control; commercial-service fit remained conditional.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-021','Brazilian Festival','2026-10-17','2026-10-17','HIST-037','WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Sponsor/vendor route — current terms recheck','Historical successor; retain occurrence without creating a new profile.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-022','South Florida Pickle Festival','2026-10-17','2026-10-18',NULL,'PURSUE','HIGH','UNRESOLVED','$500 services/lead-gen sponsor control in recovered audit','Battle Bros current vendor index confirms Oct. 17–18 event; final audit treated lead-gen route as strong.','CURRENT_WEB_VERIFIED','https://www.battlebrosevents.com/vendors',true),
('RQ4-2026-023','Jupiter Halloween Spooktacular','2026-10-17','2026-10-17',NULL,'WATCH','MEDIUM','UNRESOLVED','Sponsor route — terms recheck','Recovered municipal sponsor-lane control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-024','Spookyville — West Palm Beach','2026-10-17','2026-10-31',NULL,'WATCH','MEDIUM','UNRESOLVED','Sponsorship/package route only','Recovered multi-date Halloween control; ordinary vendor route was not treated as proven Paradise fit.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-025','Royal Palm Beach Rock-N Fall Fest','2026-10-23','2026-10-24','HIST-038','WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Historical ~$410 control — current terms recheck','Historical/non-additive occurrence retained for staffing/collision awareness.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-026','Caribbean Culture Fest — North Miami','2026-10-24','2026-10-24',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','Vendor/sponsor route; service economics confirm','Current event confirms Oct. 24 and vendor/partner route; final audit kept commercial fit gated.','CURRENT_WEB_VERIFIED','https://caribbeanculturefest.com/',true),
('RQ4-2026-027','Moose Lodge Fall Art & Craft Fair — Melbourne','2026-10-24','2026-10-24',NULL,'WATCH','LOW','PROVISIONAL_NET_NEW','$60 control in recovered audit','Cheap-test research control; event scale/fit kept below core pursue tier.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-028','Delray KidsFest','2026-10-24','2026-10-24',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','$500 / $750 / $1,000 promotional tiers in recovered audit','Recovered family-event promotional/sponsor control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-029','Indian River Lagoon Science Festival','2026-10-24','2026-10-24',NULL,'WATCH','LOW','UNRESOLVED','$75 conditional STEAM-demo control in recovered audit','Eligibility depended on a credible educational/demo activation rather than generic lead generation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-030','Sun Sentinel PRIME Expo — Boca Raton','2026-10-25','2026-10-25',NULL,'PURSUE','HIGH','HISTORICAL_NONADDITIVE','Exhibitor/sponsor route — current quote','Recovered high-priority senior/home-improvement event; later reconciliation treated it as historical successor/non-additive.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-031','Senior Lifestyle & Healthcare Expo — West Boynton','2026-10-26','2026-10-26',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$395; $350 each if 3+ in recovered audit','Final Q4 overlay said get space, subject to home-improvement eligibility confirmation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-032','Fort Lauderdale International Boat Show','2026-10-28','2026-11-01','HIST-155','WATCH','LOW','HISTORICAL_NONADDITIVE','Historical series — activation economics recheck','Historical DID-NOT-DO context retained for calendar awareness rather than canonical addition.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-033','Space Coast State Fair','2026-10-29','2026-11-15',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','Commercial vendor route — quote','Official schedule confirms Oct. 29–Nov. 15; recovered final audit retained as a high-priority commercial-vendor control.','CURRENT_WEB_VERIFIED','https://spacecoaststatefair.com/fall-schedule/',true),
('RQ4-2026-034','Vero Beach Downtown Friday — October','2026-10-30','2026-10-30',NULL,'PURSUE','HIGH','SERIES_REACTIVATION','$100 / $65 in recovered audit','Recovered low-cost downtown business/vendor control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-035','Palm Bay Fall Fest','2026-10-31','2026-10-31',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','Business trunk/vendor or sponsor route','Recovered municipal Q4 control with business participation path.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-036','LagoonFest','2026-10-31','2026-10-31',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','Sponsor lane — quote','Recovered West Palm Beach sponsor/activation control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-037','Cars & Coffee Palm Beach — November','2026-11-01','2026-11-01',NULL,'WATCH','MEDIUM','SERIES_REACTIVATION','Quote required','Recovered recurring business/vendor opportunity.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-038','Fort Pierce Friday Fest — November','2026-11-06','2026-11-06',NULL,'PURSUE','MEDIUM','SERIES_REACTIVATION','Vendor/business route — terms recheck','Recovered municipal recurring-event control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-039','NASCAR Championship Weekend — Homestead','2026-11-06','2026-11-08',NULL,'RESEARCH','HIGH','UNRESOLVED','Premium activation — quote/eligibility','Recovered premium Q4 candidate; calendar research only until a Paradise-appropriate activation path is reconfirmed.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-040','Dream Asia Festival — West Palm Beach','2026-11-06','2026-11-08',NULL,'WATCH','LOW','UNRESOLVED','Sponsorship route — commercial fit recheck','Recovered sponsorship-only control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-041','CarifestPSL','2026-11-07','2026-11-07',NULL,'WATCH','HIGH','SERIES_REACTIVATION','Commercial/vendor route; home-service approval unresolved','Final audit kept this as WATCH HIGH / pursue-test and noted legacy CACG/Treasure Coast Jerk Festival identity implications.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-042','Downtown Day of the Dead — Fort Lauderdale','2026-11-07','2026-11-07',NULL,'WATCH','MEDIUM','PORTFOLIO_CHILD','$150–$400 vendor in recovered audit','Riverwalk portfolio occurrence retained as a calendar control.','CURRENT_WEB_VERIFIED','https://www.goriverwalk.com/partners-sponsors/sponsorship-opportunities',true),
('RQ4-2026-043','Bark in the Park — Titusville','2026-11-07','2026-11-07',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','$40 10x10 in recovered audit','Recovered low-cost local-vendor event; lead-gen fit remained secondary.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-044','North Miami Health & Wellness Festival','2026-11-07','2026-11-07',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','$200 small non-profit base; commercial terms recheck','Recovered health/wellness control; Paradise category requires current commercial approval.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-045','Fay Lake FestiFALL & Chili Cook-Off','2026-11-08','2026-11-08',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','Business vendor route — terms recheck','Current tourism source corrects prior Nov. 7 memory to Sunday Nov. 8 and explicitly lists business vendors.','CURRENT_WEB_VERIFIED','https://www.visitspacecoast.com/events-calendar/list/?tribe-bar-date=2026-11-08',true),
('RQ4-2026-046','Senior Lifestyle & Healthcare Expo — Delray Beach','2026-11-09','2026-11-09',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$395; $350 each if 3+ in recovered audit','Final Q4 overlay said get space, subject to home-improvement eligibility confirmation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-047','Native Rhythms Festival','2026-11-13','2026-11-15',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','Sponsor route; vendor fit specialized','Official 2026 sponsor program is active and Renewal by Andersen is already a Platinum sponsor, proving category participation; ordinary vendor fit remains specialized.','CURRENT_WEB_VERIFIED','https://nativerhythmsfestival.com/sponsors/',true),
('RQ4-2026-048','Stuart Air Show','2026-11-13','2026-11-15',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Premium sponsor/vendor route — current terms recheck','Historical successor retained for collision/staffing awareness.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-049','Riverwalk International Food Festival','2026-11-14','2026-11-14',NULL,'PURSUE','MEDIUM','PORTFOLIO_CHILD','$1,000 / $2,500 / $5,000 sponsorships in recovered audit','Current Riverwalk sponsorship page confirms Nov. 14 occurrence.','CURRENT_WEB_VERIFIED','https://www.goriverwalk.com/partners-sponsors/sponsorship-opportunities',true),
('RQ4-2026-050','Holiday Shopping Fair — West Palm Beach','2026-11-14','2026-11-15','HIST-045','WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Commercial vendors — current rate recheck','Historical/non-additive control retained for Q4 calendar coverage.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-051','Senior Lifestyle & Healthcare Expo — Pompano Beach','2026-11-17','2026-11-17',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$395; $350 each if 3+ in recovered audit','Final Q4 overlay said get space, subject to home-improvement eligibility confirmation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-052','Turkey Bash — Pembroke Pines','2026-11-21','2026-11-21',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','Brand activation / sponsorship; prior audit $500 control','Current official sponsor page confirms brand activations and Nov. 21 at C.B. Smith Park; exact current package price should be read from application before commitment.','CURRENT_WEB_VERIFIED','https://turkey-bash.com/sponsors/',true),
('RQ4-2026-053','Port St. Lucie International Fest','2026-11-21','2026-11-21',NULL,'WATCH','MEDIUM','PORTFOLIO_CHILD','Business booth — terms recheck','Recovered PSL portfolio-child control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-054','Homestead Winter Wonderland — opening','2026-11-21','2026-11-21',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','Sponsor activation — eligibility unresolved','Verified opening-date control retained with vendor eligibility explicitly unresolved.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-055','Harvest in Miami','2026-11-21','2026-11-22',NULL,'WATCH','LOW','PROVISIONAL_NET_NEW','Vendor/sponsor route — fit recheck','Recovered lower-priority Q4 control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-056','Vero Holiday Art & Craft Expo','2026-11-21','2026-11-22',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Commercial route — current fit recheck','Historical/non-additive holiday occurrence retained.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-057','Christmas on Las Olas','2026-12-01','2026-12-01',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','10x10 business exhibit includes tent/table/chairs/electricity; quote','Official 2026 exhibit page explicitly invites businesses and requires COI.','CURRENT_WEB_VERIFIED','https://www.lasolasboulevard.com/exhibit-at-colo-2026',true),
('RQ4-2026-058','Boca Raton Holiday Street Parade','2026-12-02','2026-12-02',NULL,'WATCH','MEDIUM','UNRESOLVED','Sponsor/vendor route — fit recheck','Recovered Boca holiday calendar control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-059','Fort Pierce Friday Fest — December','2026-12-04','2026-12-04',NULL,'PURSUE','MEDIUM','SERIES_REACTIVATION','Vendor/business route — terms recheck','Recovered municipal recurring-event control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-060','Hallandale Holiday in the Park','2026-12-04','2026-12-04',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','Sponsor lane — terms recheck','Recovered municipal holiday sponsor control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-061','Space Coast Holiday Food Fest & Craft Fair','2026-12-05','2026-12-05',NULL,'PURSUE','HIGH','PROVISIONAL_NET_NEW','$500–$5,000 sponsor; business/services/lead-gen route','Current organizer publishes a sponsor application for small/large businesses, services, marketing and lead gen.','CURRENT_WEB_VERIFIED','https://www.eventeny.com/events/vendor/?id=51168',true),
('RQ4-2026-062','Port St. Lucie Festival of Lights','2026-12-05','2026-12-05',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Business booth — current terms recheck','Historical successor/identity-repair control retained without canonical inflation.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-063','Buckler West Palm Beach Craft Fair — December','2026-12-05','2026-12-06',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','$400 commercial 10x10 in recovered audit','Historical/same-series control retained for staffing/collision awareness.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-064','Venezuelan Festival — South Florida','2026-12-05','2026-12-05',NULL,'WATCH','LOW','UNRESOLVED','Sponsor/vendor route — fit recheck','Recovered lower-priority cultural-event control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-065','Cars & Coffee Palm Beach — December','2026-12-06','2026-12-06',NULL,'WATCH','MEDIUM','SERIES_REACTIVATION','Quote required','Recovered recurring business/vendor opportunity.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-066','Weston Run for Tomorrow','2026-12-06','2026-12-06',NULL,'PURSUE','MEDIUM','PROVISIONAL_NET_NEW','Sponsor/community activation — terms recheck','Recovered Q4 community activation control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-067','Martin County Winter Fest','2026-12-11','2026-12-11',NULL,'PURSUE','HIGH','UNRESOLVED','$250 10x10/sponsor control in recovered audit','Recovered strong low-cost December community-event control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-068','Palm Bay Holiday Market','2026-12-12','2026-12-12',NULL,'WATCH','MEDIUM','PROVISIONAL_NET_NEW','$60 booth + $25 category exclusivity in recovered audit','Latest audit treatment was WATCH/MEDIUM: cheap test but lower scale and Dec. 12 collision pressure.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-069','Treasure Coast Holiday Food Fest & Craft Fair','2026-12-12','2026-12-12','HIST-120','PURSUE','HIGH','HISTORICAL_NONADDITIVE','$500+ sponsor/lead-gen control in recovered audit','Current organizer index confirms Dec. 12; historical profile means zero canonical-profile delta.','CURRENT_WEB_VERIFIED','https://www.battlebrosevents.com/vendors',true),
('RQ4-2026-070','Winterfest Boat Parade — Fort Lauderdale','2026-12-12','2026-12-12',NULL,'WATCH','MEDIUM','HISTORICAL_NONADDITIVE','Sponsor/activation route — terms recheck','Recovered marquee holiday control; ordinary booth economics were not assumed.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-071','Wellington Holiday Boat Parade','2026-12-12','2026-12-12',NULL,'PURSUE','HIGH','UNRESOLVED','$50 vendor / $250 sponsor in recovered audit','Recovered low-cost Wellington holiday control; current rate should be rechecked before commitment.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-072','Delray Beach Holiday Parade','2026-12-12','2026-12-12',NULL,'WATCH','MEDIUM','UNRESOLVED','$500 / $1,000 sponsor control in recovered audit','Recovered Delray holiday sponsorship control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-073','Vero Outlets Holiday Bazaar','2026-12-12','2026-12-13',NULL,'WATCH','LOW','HISTORICAL_NONADDITIVE','Commercial vendor route — current terms recheck','Historical/non-additive holiday occurrence retained.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-074','Wellington Holiday Parade','2026-12-13','2026-12-13',NULL,'WATCH','MEDIUM','UNRESOLVED','Sponsor/vendor route — terms recheck','Recovered municipal holiday control.','RECOVERED_AUDIT',NULL,true),
('RQ4-2026-X01','Great Bridal Expo — South Florida','2026-10-04','2026-10-04',NULL,'SUPPRESS','LOW','UNRESOLVED',NULL,'Explicitly suppressed in final audit; not a standard Paradise consumer-event lane.','RECOVERED_AUDIT',NULL,false),
('RQ4-2026-X02','PalmCon','2026-11-14','2026-11-15',NULL,'SUPPRESS','LOW','UNRESOLVED',NULL,'Explicitly suppressed from ordinary Paradise lane in final audit.','RECOVERED_AUDIT',NULL,false),
('RQ4-2026-X03','Senior Expo USA — November home-improvement lane','2026-11-09','2026-11-10',NULL,'SUPPRESS','LOW','UNRESOLVED',NULL,'Home Improvement category sold out; waitlist/2027 only.','RECOVERED_AUDIT',NULL,false),
('RQ4-2026-X04','Nights of Lights — St. Augustine','2026-11-27','2026-12-31',NULL,'SUPPRESS','LOW','UNRESOLVED',NULL,'Vendor evidence was rejected/compromised in final audit; do not promote.','RECOVERED_AUDIT',NULL,false),
('RQ4-2026-X05','Jammin'' Jensen','2026-10-01','2026-12-31',NULL,'SUPPRESS','LOW','UNRESOLVED',NULL,'Excluded because ordinary business/service promotion was not allowed.','RECOVERED_AUDIT',NULL,false)
on conflict (control_id) do update set
  event_label=excluded.event_label,
  event_start=excluded.event_start,
  event_end=excluded.event_end,
  profile_id=excluded.profile_id,
  disposition=excluded.disposition,
  priority=excluded.priority,
  identity_treatment=excluded.identity_treatment,
  price_text=excluded.price_text,
  rationale=excluded.rationale,
  verification_state=excluded.verification_state,
  source_url=excluded.source_url,
  calendar_visibility=excluded.calendar_visibility,
  active=true,
  updated_at=now();
